spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dentalradiology
#   url: jdbc:postgresql://localhost:5432/"NOME DO BANCO"
    username: postgres
    password: P@sswd1941

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

server:
  port: 8080
# port: "VERIFICAR AS PORTAS NAO UTILIZADAS E FAZER UTILIZAR UMA SEM ALOCACAO"
  tomcat:
    relaxed-query-chars: '|,{,},[,]'
  servlet:
    context-path: /

auth-api:
  username: admin
  password: admin
